version: "3.8"

services:
  # Application's database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5434:5432
    volumes:
      - database-data:/var/lib/postgresql/data    
    command: -p 5432

volumes:
  database-data: